name: React Native Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - V2_Code

permissions:
  contents: write  # Needed for creating releases

jobs:
  build-android:
    name: Build & Release Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Expo prebuild (android)
        run: npm run prebuild

      - name: Grant gradlew execute permission
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Create GitHub Release for Android
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}-android
          name: Android Release v${{ steps.package-version.outputs.current-version }}
          files: android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
